app = "manhwa-downloader-bot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  auto_stop_machines = false
  auto_start_machines = true
